DevOpsCustomerView/main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('userinterface.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DevOpsCustomerView/userinterface/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.loggingout, name='logout'),
    path('overview/', views.projectList, name='overview'),
    path('reports/', views.reportOverview, name='reportOverview'),    
    path('project/<slug:slug>/<int:id>', views.projectView, name='project'),
    path('project/<slug:slug>/<int:id>/<str:hash>', views.projectPublic, name='publicOverview'),
    path('project/<slug:slug>/<int:id>/print/', views.printOverview, name='printOverview'),
    path('project/<slug:slug>/<int:id>/documentation/', views.wiki, name='wiki'),
    path('project/<slug:slug>/<int:id>/downloads/', views.fileList, name='downloads'),
    path('project/<slug:slug>/<int:id>/download/<str:file>', views.fileDownload, name='download'),
    path('project/<slug:slug>/<int:id>/documentation/print/', views.printWiki, name='printWiki'),
    path('project/<slug:slug>/<int:id>/documentation/<path:page>', views.wikiPage, name='wikiPage'),
    path('project/<slug:slug>/<int:id>/issues/', views.issueList, name='issueList'),
    path('project/<slug:slug>/<int:id>/issues/create', views.issueCreate, name='issueCreate'),
    path('project/<slug:slug>/<int:id>/issues/<int:issue>', views.issue, name='issue'),
    path('project/<slug:slug>/<int:id>/milestones/', views.milestones, name='milestones'),
    path('project/<slug:slug>/<int:id>/milestone/<int:mid>', views.milestoneBoard, name='milestoneBoard'),
    path('project/<slug:slug>/<int:id>/userSettings/', views.userSettings, name='userSettings'),
    path('cache/clear/', views.clearCache, name='clearCache'),
    path('cache/warmup/', views.warmupCache, name='warmupCache'),
]

DevOpsCustomerView/userinterface/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.conf import settings
from django.contrib.auth.models import User
from django.template.backends import django
from django.utils import timezone
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy
import os, hashlib, datetime

class TeamMember(models.Model):
    """Overwrite profile information of GitLab Users

    More information on the descision to rewrite profile data
    https://gitlab.com/software-design-public/gitlab-customer-view/-/wikis/considerations/'TeamMember'-class
    """
    def __str__(self):
        return '{} ({})'.format(self.name, self.username)

    name = models.CharField(max_length=200)
    avatar = models.ImageField(blank=True)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    homepage = models.CharField(max_length=1000,null=True,blank=True)
    username = models.CharField(max_length=200)
    
    def getActiveProjects(self):
        return self.project_set.filter(inactive=False, closed=False)

class Project(models.Model):
    """Representation of the hosted project

    This model should only contain a reference to the project and settings
    """

    class RepositoryServiceTypes(models.IntegerChoices):
            GITLAB = 1, gettext_lazy('GitLab')
            GITHUB = 2, gettext_lazy('GitHub')

    def __str__(self):
        return '{} ({})'.format(self.name, self.projectIdentifier)

    def publicAccessHash(self):
        if not self.privateUrlHash:
            self.privateUrlHash = hashlib.md5((settings.SECRET_KEY+self.projectIdentifier+datetime.datetime.now().strftime(settings.DATETIME_FORMAT)).encode('utf-8')).hexdigest()
            self.save()
        return self.privateUrlHash

    def loadRemoteProject(self):
        # ToDo: add different backends
        if self.repositoryService == self.RepositoryServiceTypes.GITLAB:
            from .tools.gitlabCache import loadProject
        elif self.repositoryService == self.RepositoryServiceTypes.GITHUB:
            from .tools.githubCache import loadProject
        return loadProject(self, UserProjectAssignment.objects.filter(project=self).first().accessToken)

    assignees = models.ManyToManyField(TeamMember, blank=True)
    name = models.CharField(max_length=500)
    image = models.ImageField(blank=True)
    publicOverviewPassword = models.CharField(max_length=64,default="",null=True,blank=True,help_text="If no password is set, the public overview page is not accessible")
    publicOverviewText = RichTextField(null=True,blank=True)
    firstEMailAddress = models.CharField(max_length=200,default=None,help_text="E-Mail Address that gets notified if a new ticket is created by the customer")
    enableDocumentation = models.BooleanField(default=True,help_text="Make the documentation accessible for users")
    enableMilestones = models.BooleanField(default=True,help_text="Visualize milestones and create a gantt chart")
    enableTicketCreation = models.BooleanField(default=True,help_text="Allow customers to create new tickets")
    enableAddComments = models.BooleanField(default=True,help_text="Allow customers to create new comments")
    enableExports = models.BooleanField(default=True,help_text="Allow users to download contents of this project")

    showSystemNotes = models.BooleanField(default=True,help_text="Show system notes together wir comments")

    labelPrefix = models.CharField(max_length=500, help_text="User are not allowed to create issues with labels that don't start with this prefix", null=True, blank=True)
    wikiPrefix =  models.CharField(max_length=500, help_text="User are not allowed to view wiki pages with paths that don't start with this prefix", null=True, blank=True)

    repositoryService = models.IntegerField(choices=RepositoryServiceTypes.choices, default=RepositoryServiceTypes.GITLAB)
    notificationLastRun = models.DateTimeField(default=timezone.now)
    # ... add more settings here

    projectIdentifier = models.CharField(max_length=200)
    privateUrlHash = models.CharField(max_length=256, null=True)

    inactive = models.BooleanField(default=False, help_text="Inactive project are marked as inactive and not shown in the overview")
    closed = models.BooleanField(default=False, help_text="If closed a project is no longer accessible or visible")

class UserProjectAssignment(models.Model):
    """Assignment between users and projects
    
    The assignment should also contain the authentication information (per user token)
    """
    def __str__(self):
        return '{} {} ({})'.format(self.user.first_name,self.user.last_name, self.project.name)

    user = models.ForeignKey(User,on_delete=models.CASCADE)
    project = models.ForeignKey(Project,on_delete=models.CASCADE)

    accessToken = models.CharField(max_length=256)

    enableNotifications  = models.BooleanField(default=False)

class DownloadableFile(models.Model):
    """Files related to a project that can be downloaded by authenticated users with project access"""

    class DownloadableFileTypes(models.IntegerChoices):
            IMPORTANT = -1, gettext_lazy('Important Files & Links')
            CLIENT = 0, gettext_lazy('Customer data')
            OFFER = 10, gettext_lazy('Offers')
            DRAFT = 20, gettext_lazy('Draft')
            ORDER = 30, gettext_lazy('Orders')
            CONTRACT = 40, gettext_lazy('Contracts')
            PRIVACY = 50, gettext_lazy('Privacy documents')
            INVOICE = 60, gettext_lazy('Invoices')
            DEVELOPMENT = 64, gettext_lazy('Development')
            PRODUCTION = 65, gettext_lazy('Production')
            DOCUMENTATION = 70, gettext_lazy('Documentation')
            OTHER = 80, gettext_lazy('Other')

    def __str__(self):
        return '{} ({})'.format(self.name, self.project.name)

    name = models.CharField(max_length=200)
    order = models.IntegerField()
    category = models.IntegerField(choices=DownloadableFileTypes.choices)
    file = models.FileField(help_text="A downloadable file - must not be added if a link is set", null=True, blank=True)
    link = models.CharField(help_text="Link to a file or document - must not be set if a file is present", max_length=2000, null=True, blank=True)
    date = models.DateField()
    project = models.ForeignKey(Project,on_delete=models.CASCADE)

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension[1:].upper()

DevOpsCustomerView/userinterface/templates/base/project/list.html
{% extends base %}
{% load i18n %}
{% load dates %}
{% load template %}

{% block content %}
<input type="text" id="searchInput" class="form-control float-end w-25 mt-1" placeholder="Search projects" onkeyup="searchProjects()">
<h1>{% trans "All your projects with us" %}</h1>
<div id="projectsHolder">
  {% for p in activeProjects %}
    {% with t='partials/project'|template %}
      {% include t with p=p %}
    {% endwith %}
  {% endfor %}
  {% for p in inactiveProjects %}
    {% with t='partials/project'|template %}
      {% include t with p=p %}
    {% endwith %}
  {% endfor %}
</div>
{% endblock %}

DevOpsCustomerView/userinterface/templates/base/project/public.html
{% extends base %}
{% load i18n %}
{% load static %}
{% load template %}

{% block content %}

  <h1>{{ localProject.name }}</h1>

  {% if request.GET.error == 'invalid' or request.GET.error == 'loginrequired' %}
    {% if request.GET.error == 'invalid' %}
      <div class="alert alert-danger">
        {% trans "The passcode you entered was not correct." %}
      </div>
      {% endif %}
      <br><br>
      {% trans "Login is required to access information on this dashboard. Please enter the passcode below to access this page." %}
      <br><br>
      <form method="POST" action="/project/{{ remoteProject.path }}/{{ remoteProject.remoteIdentifier }}/{{ localProject.publicAccessHash }}">
        {% csrf_token %}
        <div class="row">
          <div class="col-lg-6">
            <div class="input-group mb-3">
                  <input type="text" name="password" class="form-control form-control-lg" placeholder="{% trans "Enter passcode" %}" aria-label="{% trans "Enter passcode" %}" aria-describedby="button-addon2">
                  <input class="btn btn-outline-secondary" type="submit" id="button-addon2" value="{% trans "Request access" %}">
            </div>
          </div>
        </div> 
      </form>
  {% else %}
  <br>
  <div class="row">
    <div class="col-2">
      <img class="w-100" src="{% if localProject.image %}{{ localProject.image.url }}{% else %}{{ remoteProject.avatar_url }}{% endif %}" alt="{% trans "No image found" %}">
    </div>
    <div class="col-6">
      {% if localProject.publicOverviewText %}
        {{ localProject.publicOverviewText|safe }}
      {% else %}
        {{ remoteProject.description }}
      {% endif %}
    </div>
    <div class="col-4">
      <br>
        <div class="row">
          {% for type, label in fileTypes.DownloadableFileTypes.choices %}
            {% with relatedFiles=localProject.downloadablefile_set|in_category:type %}
              {% if relatedFiles|length > 0 %}
              <div class="box">
                <div class="col-12">
                  <br>
                  <h4>{{ label }}</h4>
                  {% with t='partials/files'|template %}
                    {% include t with files=relatedFiles%}
                  {% endwith %}
                </div>
              </div>
              {% endif %} 
            {% endwith %}
          {% endfor %}
        </div>
        <br />
    </div>
  </div>
  {% endif %}
  
{% endblock %}

DevOpsCustomerView/userinterface/templates/base/project/userSettings.html
{% extends base %}
{% load i18n %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
        <h1>{{ localProject.name }}</h1>
        <h2>{% trans "Project settings" %}</h2>
      <br><br>
    </div>
    <div class="col-5">
      <form class="" method="post">
          {% csrf_token %}
          <h4 class="h4 mb-3 font-weight-normal">{% trans "Notifications" %}</h4>
          <label for="enableNotifications" class="">{% trans "Send email notifications for changes" %}</label>
          <input type="checkbox" name="enableNotifications" value="enable" {% if enableNotifications %} checked {% endif %}>
          <br><br><br>
          <input type="submit" class="btn btn-primary float-start">
        </form>
      <br>
    </div>
  </div>
</div>
{% endblock %}

DevOpsCustomerView/userinterface/templates/base/project/view.html
{% extends base %}
{% load i18n %}
{% load static %}
{% load dates %}
{% load template %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'vendor/frappe-gantt/frappe-gantt.min.css' %}">
{% endblock %}

{% block extra_js %}
  {% if allMilestones %}
    <script nonce="{{ request.csp_nonce }}" src="{% static 'vendor/frappe-gantt/frappe-gantt.js' %}"></script>
    <script nonce="{{ request.csp_nonce }}">
      var tasks = [
      {% for milestone in allMilestones %} 
        
        {% if milestone.start_date and milestone.due_date %}
          {% with milestone.due_date|dayssince as dayssince %}
            {% if milestone.expired == False or milestone.expired == True and dayssince < 365 %}
            {
              id: '{{ milestone.id }}',
              name: '{{ milestone.title }}',
              start: '{{ milestone.start_date|date:"Y-m-d"|default:"2020-01-01" }}',
              end: '{{ milestone.due_date|date:"Y-m-d"|default:"2020-01-01" }}',
              progress: 0,
            },
            {% endif %}
          {% endwith %}
        {% endif %}
      {% endfor %}
      ]
      var gantt = new Gantt(document.querySelector('#gantt'), tasks, {
          header_height: 50,
          column_width: 30,
          step: 24,
          bar_height: 40,
          bar_corner_radius: 0,
          arrow_curve: 5,
          padding: 18,
          custom_popup_html: function(task) {
            window.location = '/project/{{ remoteProject.path }}/{{ remoteProject.remoteIdentifier }}/milestone/'+task.remoteIdentifier;
            return ``;
          },
          {% if daysbetween < 180 %}
            view_mode: 'Week',
          {% elif daysbetween < 730 %}
            view_mode: 'Month',
          {% else %}
            view_mode: 'Year',
          {% endif %}
          date_format: 'YYYY-MM-DD',
      });

      const oldest = gantt.get_oldest_starting_date().getTime()
      const t = new Date() - oldest
      gantt.gantt_start = new Date(gantt.gantt_start.getTime() - t)
      gantt.set_scroll_position()
    </script>
  {% endif %}
{% endblock %}

{% block content %}
<div class="btn-group float-end" role="group">
  {% if localProject.enableTicketCreation %}
  <a href="/project/{{ remoteProject.path }}/{{ remoteProject.remoteIdentifier }}/issues/create" class="btn btn-outline-primary"><i class="fa far fa-plus"></i> {% trans "Create Ticket" %}</a>
  {% endif %}
  {% if localProject.enableMilestones %}
  <a href="/project/{{ remoteProject.path }}/{{ remoteProject.remoteIdentifier }}/milestones/" class="btn btn-outline-primary"><i class="fa far fa-tasks"></i> {% trans "Milestones" %}</a>
  {% endif %}
  {% if wikiPages and localProject.enableDocumentation  %}
  <a href="/project/{{ remoteProject.path }}/{{ remoteProject.remoteIdentifier }}/documentation/" class="btn btn-outline-primary"><i class="fa far fa-book"></i> {% trans "Documentation" %}</a>
  {% endif %}
  {% if request.user.is_superuser %}
  <a href="{{ remoteProject.web_url }}" class="btn btn-outline-primary" target="_blank"><i class="fab fa-gitlab"></i></a>
  {% endif %}
</div>

<h1>{{ localProject.name }}</h1>
  {% if allMilestones %}
    {{ remoteProject.description }}
  {% endif %}
  <br><br>
  <div class="row">
    <div class="col-3">
      <img class="w-100" src="{% if localProject.image %}{{ localProject.image.url }}{% else %}{{ remoteProject.avatar_url }}{% endif %}" alt="{% trans "No image found" %}">
    </div>
    <div class="col-9">
      {% if not allMilestones %}
        {{ remoteProject.description }}
      {% else %}
      <br>
      <svg id="gantt"></svg>
      {% endif %}
    </div>
    <div class="col-8">
      <br>
      <h4>{% trans "Last updated issues" %}</h4><br>
      <ul class="list-group">
        {% with t='partials/issues'|template %}
          {% include t with issues=mostRecentIssues milestones=True %}
        {% endwith %}
      </ul>
      <br>
      <div class="btn-group float-end" role="group">
        <a href="/project/{{ remoteProject.path }}/{{ remoteProject.remoteIdentifier }}/issues/" class="btn btn-outline-primary"><i class="fa far fa-plus"></i> {% trans "All issues" %} &raquo;</a>
      </div>
      <br>
    </div>
    <div class="col-4">
      <br>
      <h4>{% trans "Person in charge" %}</h4><br>
      <div class="row">
        {% for assignee in localProject.assignees.all %}
          <div class="col-md-12 pb-3">
            {% with t='partials/employee'|template %}
              {% include t with employee=assignee %}
            {% endwith %}
          </div>
        {% endfor %}
      </div>
      {% if localProject.downloadablefile_set.count > 0 or projectReleases|length > 0 %}
        <br>
        <h4>{% trans "Documents & Downloads" %}</h4>
        {% blocktrans with amountFiles=localProject.downloadablefile_set.count amountRelease=projectReleases|length %}
        There are {{ amountFiles }} file(s) and {{ amountRelease }} release(s) attached to this project.
        {% endblocktrans %}
        <br><br>
        <a href="/project/{{ remoteProject.path }}/{{ remoteProject.remoteIdentifier }}/downloads/" class="btn btn-outline-primary"><i class="fa far fa-download"></i> {% trans "Documents & Downloads" %}</a>
      {% endif %}
    </div>
  </div>
  
{% endblock %}